"""add 'name' field to 'Operation' table

Revision ID: 0999eb118480
Revises: ff06202e0ee6
Create Date: 2021-09-23 19:50:44.665788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0999eb118480'
down_revision = 'ff06202e0ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'name')
    # ### end Alembic commands ###
